const quizData = {
    // ---- COMPUTER SCIENCE ----
    cs_ds: [
        { q: "What is the time complexity of a binary search tree in the worst case?", options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"], correct: 1, exp: "In the worst case (unbalanced tree), it becomes a linked list with O(n) search time.", difficulty: "medium" },
        { q: "Which data structure uses LIFO (Last In First Out)?", options: ["Queue", "Stack", "Tree", "Graph"], correct: 1, exp: "Stack follows LIFO. The last element added is the first one to be removed.", difficulty: "easy" },
        { q: "What data structure is used to implement a Priority Queue?", options: ["Array", "Linked List", "Heap", "Hash Table"], correct: 2, exp: "A Heap (min-heap or max-heap) efficiently supports priority queue operations.", difficulty: "medium" },
        { q: "In a Hash Table, what handles the scenario where two keys map to the same index?", options: ["Garbage Collection", "Collision Resolution", "Tree Balancing", "Virtual Memory"], correct: 1, exp: "Collision resolution techniques like Chaining or Open Addressing handle this.", difficulty: "easy" },
        { q: "Which sorting algorithm is heavily utilized in the standard library of many languages due to its average O(n log n) efficiency?", options: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Quick Sort / Merge Sort"], correct: 3, exp: "Variants of Quick Sort or Merge Sort (like Timsort) are the industry standard for general bounds.", difficulty: "easy" },
        { q: "What is the minimum number of edges to make a connected graph with N vertices?", options: ["N", "N-1", "N+1", "2N"], correct: 1, exp: "A tree is the minimally connected graph, which has exactly N-1 edges.", difficulty: "medium" },
        { q: "A B-Tree is primarily used in which of the following systems?", options: ["Machine Learning", "Operating System Kernels", "Database systems", "Network Routers"], correct: 2, exp: "B-Trees are optimized for systems that read and write large blocks of data, like databases.", difficulty: "hard" },
        { q: "Which graph traversal protocol uses a Queue?", options: ["Depth First Search (DFS)", "Breadth First Search (BFS)", "Dijkstra's Algorithm", "A* Algorithm"], correct: 1, exp: "BFS explores layer by layer, utilizing a Queue to track the next nodes to visit.", difficulty: "easy" },
        { q: "What is the maximum number of children for a node in a Red-Black Tree?", options: ["1", "2", "3", "Log N"], correct: 1, exp: "A Red-Black tree is a type of binary search tree, so each node has at most 2 children.", difficulty: "medium" },
        { q: "Which of these is a non-linear data structure?", options: ["Array", "String", "Stack", "Graph"], correct: 3, exp: "Arrays, stacks, and strings are linear. Graphs and Trees are non-linear.", difficulty: "easy" }
    ],
    cs_os: [
        { q: "What is the primary objective of multiprogramming?", options: ["Increase CPU utilization", "Increase disk speed", "Provide UI", "Increase memory size"], correct: 0, exp: "Multiprogramming keeps the CPU continually busy by organizing jobs so that the CPU always has one to execute.", difficulty: "easy" },
        { q: "What is a 'deadlock'?", options: ["Software crash", "Circular wait for resources", "Hard drive failure", "Memory leak"], correct: 1, exp: "Deadlock is a state where processes wait indefinitely for resources held by each other.", difficulty: "medium" },
        { q: "Which scheduling algorithm assigns the CPU to the process with the smallest execution time?", options: ["Round Robin", "FCFS", "SJF (Shortest Job First)", "Priority Scheduling"], correct: 2, exp: "Shortest Job First (SJF) minimizes average waiting time.", difficulty: "easy" },
        { q: "What is Virtual Memory?", options: ["Cache memory", "RAM expansion physically", "Illusion of larger memory backed by disk", "ROM"], correct: 2, exp: "Virtual memory uses hardware and software to allow a computer to compensate for physical memory shortages by temporarily transferring data from RAM to disk.", difficulty: "medium" },
        { q: "Which concept allows multiple threads to prevent concurrent access to shared resources?", options: ["Pipeline", "Semaphore/Mutex", "Cache", "Interrupts"], correct: 1, exp: "Mutexes and semaphores provide synchronization to prevent race conditions during concurrent execution.", difficulty: "hard" },
        { q: "What specifies the exact location of a page in physical memory?", options: ["Page Table", "TLB", "Index Register", "Cache Directory"], correct: 0, exp: "The hardware uses a page table to translate logical addresses to physical addresses.", difficulty: "medium" },
        { q: "Belady's Anomaly occurs in which page replacement algorithm?", options: ["LRU", "Optimal", "FIFO", "LFU"], correct: 2, exp: "In FIFO, increasing the number of page frames can unexpectedly increase the number of page faults.", difficulty: "hard" },
        { q: "A context switch involves saving the state of the old process and loading the saved state of the new process. Where is this state stored?", options: ["Hard Disk", "PCB (Process Control Block)", "Main Memory exclusively", "Cache exclusively"], correct: 1, exp: "The OS maintains a PCB for each process, holding its registers, counter, and state.", difficulty: "medium" },
        { q: "Which of the following is not an OS?", options: ["Linux", "Windows", "Oracle", "macOS"], correct: 2, exp: "Oracle is primarily known for its Database Management System.", difficulty: "easy" },
        { q: "What is Thrashing?", options: ["Disk cleaning", "Excessive paging activity causing performance collapse", "CPU overheating", "Fast cache hits"], correct: 1, exp: "Thrashing occurs when the OS spends more time paging than executing processes.", difficulty: "hard" }
    ],

    // ---- ELECTRICAL ENGINEERING ----
    ee_c: [
        { q: "According to Kirchhoff's Current Law (KCL), the algebraic sum of currents entering a node is:", options: ["Positive", "Negative", "Zero", "Infinite"], correct: 2, exp: "KCL states that charge cannot accumulate at a node, so sum of currents entering equals sum leaving.", difficulty: "easy" },
        { q: "What is the equivalent resistance of three 6-ohm resistors in parallel?", options: ["18 ohms", "2 ohms", "6 ohms", "3 ohms"], correct: 1, exp: "1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2. Therefore R_eq = 2 ohms.", difficulty: "medium" },
        { q: "Thevenin's theorem reduces a linear circuit to a single voltage source in series with a:", options: ["Capacitor", "Current Source", "Inductor", "Resistor"], correct: 3, exp: "Thevenin's equivalent consists of a voltage source (Vth) and a series resistance (Rth).", difficulty: "easy" },
        { q: "What is the time constant of an RC circuit?", options: ["R/C", "C/R", "RC", "1/(RC)"], correct: 2, exp: "The time constant tau (τ) is equal to Resistance times Capacitance.", difficulty: "medium" },
        { q: "In AC circuit analysis, an inductor causes the current to:", options: ["Lead the voltage by 90°", "Lag the voltage by 90°", "Be in phase with the voltage", "Lag by 180°"], correct: 1, exp: "ELI the ICE man: In an Inductor (L), Voltage (E) leads Current (I) by 90 degrees. In a Capacitor (C), Current (I) leads Voltage (E).", difficulty: "hard" },
        { q: "Which component exhibits a nonlinear I-V characteristic?", options: ["Resistor", "Diode", "Ideal Capacitor", "Ideal Inductor"], correct: 1, exp: "A diode's current is exponentially proportional to the voltage applied across it.", difficulty: "easy" },
        { q: "Maximum power transfer occurs when the load resistance equals the:", options: ["Source voltage", "Norton current", "Source resistance", "Zero"], correct: 2, exp: "According to the Maximum Power Transfer theorem, RL must equal Rth (source resistance).", difficulty: "medium" },
        { q: "The unit of Admittance is:", options: ["Ohm", "Farad", "Siemens", "Henry"], correct: 2, exp: "Admittance is the inverse of impedance, measured in Siemens (or Mhos).", difficulty: "easy" },
        { q: "A step-down transformer has:", options: ["More primary turns than secondary turns", "More secondary turns than primary turns", "Equal turns", "No coils"], correct: 0, exp: "Voltage ratio is proportional to turns ratio. To step down voltage, primary turns must exceed secondary turns.", difficulty: "medium" },
        { q: "What happens to the impedance of a capacitor as frequency increases?", options: ["Increases", "Decreases", "Stays the same", "Becomes infinite"], correct: 1, exp: "Zc = 1 / (j*w*C). As frequency (w) increases, the impedance decreases.", difficulty: "hard" }
    ],
    ee_s: [
        { q: "The Fourier transform represents a signal in which domain?", options: ["Time domain", "Frequency domain", "Spatial domain", "Logical domain"], correct: 1, exp: "Fourier transform decomposes a function of time into its constituent frequencies.", difficulty: "easy" },
        { q: "What does the Nyquist theorem state regarding sampling rate?", options: ["Fs = 1/Fmax", "Fs < Fmax", "Fs >= 2 * Fmax", "Fs = Fmax"], correct: 2, exp: "To perfectly reconstruct a signal, it must be sampled at twice the highest frequency present.", difficulty: "medium" },
        { q: "A system is Linear if it satisfies:", options: ["Superposition and Homogeneity", "Time invariance", "Causality", "Stability"], correct: 0, exp: "A linear system obeys both the principles of additivity (superposition) and scaling (homogeneity).", difficulty: "medium" },
        { q: "What type of filter allows only high frequencies to pass?", options: ["Low-pass filter", "Band-pass filter", "High-pass filter", "Notch filter"], correct: 2, exp: "A high-pass filter attenuates frequencies lower than the cutoff frequency.", difficulty: "easy" },
        { q: "Convolution in the time domain is equivalent to what in the frequency domain?", options: ["Addition", "Derivative", "Convolution", "Multiplication"], correct: 3, exp: "The convolution theorem states that time-domain convolution is equivalent to frequency-domain multiplication.", difficulty: "hard" },
        { q: "Which tool is used for analyzing discrete-time systems, analogous to the Laplace transform for continuous-time?", options: ["Z-transform", "Fourier Series", "Mellin transform", "Hilbert transform"], correct: 0, exp: "The Z-transform converts a discrete-time signal into a complex frequency-domain representation.", difficulty: "medium" },
        { q: "An impulse response completely characterizes which type of system?", options: ["Non-linear Time Variant", "Linear Time-Invariant (LTI)", "Causal non-linear", "Stochastic"], correct: 1, exp: "LTI systems are fully described by their impulse response via convolution.", difficulty: "hard" },
        { q: "What characterizes a causal system?", options: ["Depends on future inputs", "Depends only on present and past inputs", "Is always stable", "Has zero margin of error"], correct: 1, exp: "Causal systems do not anticipate future inputs.", difficulty: "easy" },
        { q: "Aliasing occurs when:", options: ["Sampling rate is too high", "Signal is amplified strictly", "Sampling rate is lower than the Nyquist rate", "The filter is analog"], correct: 2, exp: "Sub-Nyquist sampling causes higher frequencies to fold into lower frequencies, causing aliasing.", difficulty: "medium" },
        { q: "The region of convergence (ROC) of a causal stable discrete-time system must include:", options: ["Only the origin", "The unit circle", "The imaginary axis", "Infinity"], correct: 1, exp: "For a discrete-time LTI system to be stable, the unit circle must be within the Z-transform's ROC.", difficulty: "hard" }
    ],

    // ---- MECHANICAL ENGINEERING ----
    me_t: [
        { q: "What does the Second Law of Thermodynamics state?", options: ["Energy cannot be created", "The entropy of an isolated system always increases", "Absolute zero is reachable", "Mass is conserved"], correct: 1, exp: "It states that isolated systems spontaneously evolve towards thermodynamic equilibrium (max entropy).", difficulty: "easy" },
        { q: "Which cycle provides the foundation for the theoretical maximum efficiency of a heat engine?", options: ["Otto cycle", "Carnot cycle", "Diesel cycle", "Rankine cycle"], correct: 1, exp: "The Carnot cycle is a reversible theoretical cycle yielding the maximum possible efficiency.", difficulty: "medium" },
        { q: "In an Isothermal process, what property remains constant?", options: ["Pressure", "Volume", "Entropy", "Temperature"], correct: 3, exp: "Iso = same, Thermal = temperature. The temperature of the system is constant.", difficulty: "easy" },
        { q: "What is Enthalpy?", options: ["Heat entirely converted to work", "Total heat content of a system (U + PV)", "The measure of disorder", "Kinetic energy"], correct: 1, exp: "Enthalpy is a thermodynamic quantity equal to internal energy plus pressure times volume.", difficulty: "medium" },
        { q: "A throttling process (like fluid passing through a valve) is assumed to be:", options: ["Isentropic", "Isobaric", "Isenthalpic", "Isochoric"], correct: 2, exp: "In an ideal throttling process, no heat is exchanged and no work is done, making enthalpy constant (isenthalpic).", difficulty: "hard" },
        { q: "The specific heat at constant pressure (Cp) is always _____ the specific heat at constant volume (Cv).", options: ["Less than", "Equal to", "Greater than", "Unrelated to"], correct: 2, exp: "Cp > Cv because at constant pressure, work must also be done by the expanding gas against the surroundings.", difficulty: "medium" },
        { q: "Which engine cycle works on constant pressure heat addition?", options: ["Otto", "Diesel", "Dual", "Stirling"], correct: 1, exp: "The ideal Diesel cycle assumes heat is added at constant pressure.", difficulty: "medium" },
        { q: "The Triple Point of water is where:", options: ["Water boils instantly", "Solid, liquid, and vapor phases coexist in equilibrium", "Water achieves maximum density", "Ice stops melting"], correct: 1, exp: "At specific temperature and pressure, all three phases of water exist simultaneously.", difficulty: "easy" },
        { q: "What happens to the efficiency of a Carnot Engine if the sink temperature is decreased?", options: ["Decreases", "Remains same", "Increases", "Becomes zero"], correct: 2, exp: "Efficiency = 1 - (T_sink/T_source). Lowering T_sink increases the efficiency.", difficulty: "hard" },
        { q: "Heat transfer via electromagnetic waves is known as:", options: ["Conduction", "Convection", "Radiation", "Advection"], correct: 2, exp: "Radiation requires no medium and transfers energy via electromagnetic waves.", difficulty: "easy" }
    ],
    me_m: [
        { q: "Newton's Second Law of Motion relates force to:", options: ["Mass and Velocity", "Mass and Acceleration", "Displacement and Time", "Energy and Work"], correct: 1, exp: "Force = mass x acceleration (F = ma).", difficulty: "easy" },
        { q: "What is defined as the tendency of an object to resist changes in its state of motion?", options: ["Friction", "Momentum", "Inertia", "Gravity"], correct: 2, exp: "Inertia depends on mass; heavier objects resist motion changes more.", difficulty: "easy" },
        { q: "The rotational equivalent of Force is called:", options: ["Angular Momentum", "Torque", "Centripetal Force", "Inertia"], correct: 1, exp: "Torque (τ) causes an object to acquire angular acceleration.", difficulty: "easy" },
        { q: "Which law explains why forces always occur in equal and opposite pairs?", options: ["Newton's 1st Law", "Newton's 2nd Law", "Newton's 3rd Law", "Hooke's Law"], correct: 2, exp: "For every action, there is an equal and opposite reaction.", difficulty: "medium" },
        { q: "In mechanics, the coefficient of restitution (e) for a perfectly elastic collision is:", options: ["0", "0.5", "1", "Infinity"], correct: 2, exp: "e = 1 means no kinetic energy is lost in the collision.", difficulty: "medium" },
        { q: "What is Hooke's Law?", options: ["F = mv", "F = kx", "E = mc^2", "P = W/t"], correct: 1, exp: "The force needed to extend or compress a spring by some distance scales linearly with respect to that distance.", difficulty: "medium" },
        { q: "The center of mass of a uniform solid hemisphere of radius R lies at what distance from its base?", options: ["R/2", "R/3", "3R/8", "4R/3pi"], correct: 2, exp: "By integrating the volume, the COM of a solid hemisphere is 3R/8 from the flat base.", difficulty: "hard" },
        { q: "Static friction is generally _____ kinetic friction.", options: ["Less than", "Equal to", "Greater than", "Inversely proportional to"], correct: 2, exp: "It takes more force to initiate relative motion (static) than to maintain it (kinetic).", difficulty: "medium" },
        { q: "A flywheel stores energy in the form of:", options: ["Potential Energy", "Translational Kinetic Energy", "Rotational Kinetic Energy", "Strain Energy"], correct: 2, exp: "A rotating flywheel stores kinetic energy proportional to its moment of inertia and the square of angular velocity.", difficulty: "hard" },
        { q: "What theorem states that the work done by the net force on a particle equals the change in the particle's kinetic energy?", options: ["Parallel Axis Theorem", "Work-Energy Theorem", "Impulse-Momentum Theorem", "Castigliano's Theorem"], correct: 1, exp: "Work-Energy theorem links the work done to the change in kinetic energy of the system.", difficulty: "easy" }
    ],

    // ---- CIVIL ENGINEERING ----
    ce_sa: [
        { q: "What type of stress occurs when forces pull apart a structural member?", options: ["Compressive", "Shear", "Tensile", "Torsional"], correct: 2, exp: "Tensile stress elongates a material.", difficulty: "easy" },
        { q: "Which of the following supports prevents all translations and rotations?", options: ["Roller", "Pin", "Fixed", "Hinge"], correct: 2, exp: "A fixed support provides three reactions: vertical, horizontal, and a resisting moment.", difficulty: "medium" },
        { q: "The bending moment at a free end of a cantilever beam is always:", options: ["Maximum", "Minimum", "Zero", "Unpredictable"], correct: 2, exp: "Because there is no material past the free end to resist rotation, the internal moment must be zero.", difficulty: "medium" },
        { q: "What does the Area Moment of Inertia measure?", options: ["A body's resistance to angular acceleration", "A cross-section's resistance to bending", "Material density", "Shear strength"], correct: 1, exp: "Area moment of inertia (I) determines the stiffness of a beam strictly based on its cross-sectional geometry.", difficulty: "hard" },
        { q: "A simply supported beam with a point load exactly at mid-span will have its maximum shear force at:", options: ["Mid-span", "The supports", "Quarter span", "Center of gravity"], correct: 1, exp: "The shear force is constant from the support to the load, meaning max shear is V = P/2 near the supports.", difficulty: "hard" },
        { q: "Which material is renowned for high compressive strength but very low tensile strength?", options: ["Steel", "Wood", "Concrete", "Aluminum"], correct: 2, exp: "Concrete easily crushes rock-solid under compression but cracks rapidly under applied tension.", difficulty: "easy" },
        { q: "What is buckling?", options: ["Tensile failure", "A sudden lateral deflection of a slender column under compression", "Surface scratching", "Fatigue over time"], correct: 1, exp: "Buckling is an instability failure mode characteristic of long, slender compression members.", difficulty: "medium" },
        { q: "Which theorem is used to find deflection of linear elastic structures utilizing strain energy?", options: ["Euler's Theorem", "Castigliano's Theorem", "Mohr's Circle", "Maxwell's Reciprocal Theorem"], correct: 1, exp: "Castigliano's second theorem calculates deflection by taking the partial derivative of strain energy.", difficulty: "hard" },
        { q: "A statically indeterminate structure has:", options: ["No reactions", "More unknown reactions than equilibrium equations", "Fewer reactions than equilibrium equations", "Zero deflection"], correct: 1, exp: "Indeterminate structures require compatibility equations (deflection constraints) in addition to statics to solve.", difficulty: "medium" },
        { q: "The neutral axis of a beam undergoes what stress during pure bending?", options: ["Maximum tension", "Maximum compression", "Zero bending stress", "Maximum shear"], correct: 2, exp: "The neutral axis is the layer where longitudinal fibers do not change length, experiencing zero bending stress.", difficulty: "easy" }
    ],
    ce_fm: [
        { q: "What is defined as mass per unit volume?", options: ["Specific Gravity", "Density", "Viscosity", "Pressure"], correct: 1, exp: "Density (ρ) = m / V.", difficulty: "easy" },
        { q: "According to Bernoulli's principle, an increase in fluid velocity results in:", options: ["Increased pressure", "Decreased pressure", "Increased temperature", "No change"], correct: 1, exp: "Bernoulli's principle establishes the inverse relationship between dynamic and static pressure for steady flow.", difficulty: "easy" },
        { q: "Which number defines the ratio of inertial forces to viscous forces?", options: ["Mach Number", "Froude Number", "Reynolds Number", "Weber Number"], correct: 2, exp: "Reynolds number predicts flow patterns; high Re indicates turbulent flow.", difficulty: "medium" },
        { q: "What does Pascal's law state?", options: ["Pressure increases with depth", "Pressure is constant everywhere in an enclosed static fluid", "Pressure applied to an enclosed fluid is transmitted undiminished", "Fluid velocity is constant"], correct: 2, exp: "This is the principle heavily utilized in hydraulic lifting systems.", difficulty: "medium" },
        { q: "Viscosity of a fluid is primarily its resistance to:", options: ["Boiling", "Freezing", "Shear flow", "Compression"], correct: 2, exp: "Viscosity describes a fluid's internal resistance to gradual deformation by shear stress.", difficulty: "easy" },
        { q: "In open channel flow, if the Froude number is exactly 1, the flow is:", options: ["Subcritical", "Supercritical", "Critical", "Turbulent"], correct: 2, exp: "Fr = 1 signifies critical flow where flow velocity equals wave propagation velocity.", difficulty: "hard" },
        { q: "Cavitation in pumps occurs due to:", options: ["Excessive pressure", "Temperature drop", "Pressure dropping below the fluid's vapor pressure", "Air leaking in"], correct: 2, exp: "When local pressure drops below vapor pressure, bubbles form and violently collapse, causing damage.", difficulty: "hard" },
        { q: "The pitot tube is used primarily to measure:", options: ["Fluid density", "Fluid velocity", "Channel width", "Viscosity"], correct: 1, exp: "A pitot tube measures stagnation pressure to calculate fluid flow velocity.", difficulty: "medium" },
        { q: "Which phenomenon causes water to rise in a narrow glass tube?", options: ["Buoyancy", "Capillary action", "Cavitation", "Water hammer"], correct: 1, exp: "Capillary action results from the combination of adhesive and cohesive surface tension forces.", difficulty: "medium" },
        { q: "What is a characteristic of ideal fluid?", options: ["Highly viscous", "Compressible", "Incompressible and non-viscous", "High boundary shear"], correct: 2, exp: "An ideal fluid is a theoretical concept used to simplify fluid dynamics models, assuming zero viscosity and incompressibility.", difficulty: "easy" }
    ]
};
